### ISSUE TITLE
experimental formation energy

### ISSUE THREAD

**Issue by xingfenghe** [materialsproject/mapidoc#8]
Hi, I am wondering whether the experimental formation energy is public. For example, the Li2O has experimental formation energy on MP as -2.06 eV/atom. But I didn't find the corresponding property in the api.

Thanks in advance.

**Comment by shyuep** [comment]
The experimental formation energy is public, but it is not part of the query API. If you are using pymatgen, you can actually use the MPRester.get_exp_entry function to get the formation enthalpy for Li2O. Note that the exp data set is much smaller than the computed data set. They are essentially numbers obtained from the NIST Webbook and the Kubaschewski Tables.

**Comment by dwinston** [comment]
There is no property corresponding to experimental thermochemical data in documents of our materials collection, and thus no corresponding subdirectory within the _materials_ folder in this documentation repository, because such data maps to a chemical formula only and not to a unique _material_ (essentially a pair of (chemical formula, crystal structure)).

We store the experimental data in a separate collection; although it is accessible via our HTTP API (e.g. https://www.materialsproject.org/rest/v1/materials/Fe2O3/exp (requires an API key) -- see https://materialsproject.org/docs/api), the representation of the response is formatted for use by pymatgen, so I recommend using pymatgen (or at least consulting its code) when constructing your application.

**Comment by xingfenghe** [comment]
Thanks a lot for your help.
